language: python

python:
  - "3.8"

cache: pip

install:
  - pip install -r requirements.txt

script:
  - make html

before_deploy:
  - touch build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build/html/
  verbose: true
  on:
    branch: master
