language: python

python:
  - "3.8"

cache: pip

install:
  - pip install -r requirements.txt

script:
  - make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build/html/
  verbose: true
  on:
    branch: master
